
#This is a generic configuration file for the webservice.
#It will only be used when there is no host-specific configuration file
#(trivy.\$HOSTNAME.yml)
root: /tmp/trivy-userdata
port: 8081
#use_forwarded_host: true #(enable this if you run behind a properly configured reverse proxy only)
